"""Add Transaction, Shopping, Goal, Report, and AI tables

Revision ID: 4fe8cfef1473
Revises: d9e4f9ecb057
Create Date: 2025-11-19 14:07:43.567247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe8cfef1473'
down_revision: Union[str, Sequence[str], None] = 'd9e4f9ecb057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- 1. Create transactions table ---
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), index=True, nullable=False),
    sa.Column('budget_month', sa.String(length=7), nullable=False),
    sa.Column('category_id', sa.Integer(), sa.ForeignKey('categories.id'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('ai_category_confidence', sa.Float(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # --- 2. Create goals table ---
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), index=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('saved_amount', sa.Float(), nullable=False),
    sa.Column('monthly_contribution', sa.Float(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # --- 3. Create shopping_lists table ---
    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), index=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), sa.ForeignKey('categories.id'), nullable=False),
    sa.Column('items_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # --- 4. Create monthly_reports table ---
    op.create_table('monthly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), index=True, nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=False),
    sa.Column('total_expenses', sa.Float(), nullable=False),
    sa.Column('total_saved', sa.Float(), nullable=False),
    sa.Column('net_surplus', sa.Float(), nullable=False),
    sa.Column('category_breakdown_json', sa.Text(), nullable=False),
    sa.Column('insights_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    
    # --- 5. Create insights_ai table ---
    op.create_table('insights_ai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), index=True, nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('ai_endpoint', sa.String(length=50), nullable=False),
    sa.Column('ai_output_json', sa.Text(), nullable=False),
    sa.Column('category_prediction_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop new tables in reverse order of creation
    op.drop_table('insights_ai')
    op.drop_table('monthly_reports')
    op.drop_table('shopping_lists')
    op.drop_table('goals')
    op.drop_table('transactions')
    
    # ### end Alembic commands ###