"""Add missing foreign key indexes and updates to existing tables

Revision ID: 63d3f1de38b4
Revises: 4fe8cfef1473
Create Date: 2025-11-19 14:11:40.020931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d3f1de38b4'
down_revision: Union[str, Sequence[str], None] = '4fe8cfef1473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- 1. Update 'categories' table ---
    with op.batch_alter_table('categories', schema=None) as batch_op:
        
        # REMOVED: batch_op.add_column(sa.Column('actual', sa.Float(), server_default='0.0', nullable=False))
        # Reason: Database already reported 'actual' column exists.
        
        # Add a combined index for efficiency in querying categories per user/month (Optional)
        batch_op.create_index(batch_op.f('ix_categories_user_month'), ['user_id', 'budget_month'], unique=False)


    # --- 2. Update 'budgets' table ---
    # Add the crucial unique constraint (user_id, month)
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        # Add UNIQUE constraint to prevent duplicate budgets for the same user/month
        batch_op.create_unique_constraint('uq_budgets_user_month', ['user_id', 'month'])


    # --- 3. Update 'monthly_reports' table (from previous migration) ---
    with op.batch_alter_table('monthly_reports', schema=None) as batch_op:
        # Drop the single column unique constraint first (if it was created in the last step)
        try:
            # Drop the incorrect single-column constraint on 'month'
            batch_op.drop_constraint('monthly_reports_month_key', type_='unique') 
        except Exception:
            pass 
            
        # Add the correct composite UNIQUE constraint (user_id, month)
        batch_op.create_unique_constraint('uq_reports_user_month', ['user_id', 'month'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- 1. Downgrade 'monthly_reports' table ---
    with op.batch_alter_table('monthly_reports', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reports_user_month', type_='unique')
        # Re-add single 'month' unique constraint if desired
        # batch_op.create_unique_constraint('monthly_reports_month_key', ['month'])


    # --- 2. Downgrade 'budgets' table ---
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_budgets_user_month', type_='unique')
    
    
    # --- 3. Downgrade 'categories' table ---
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_user_month'))
        # If you were to drop the 'actual' column, you'd put it here:
        # batch_op.drop_column('actual') 
        
    # ### end Alembic commands ###